apiVersion: v1
kind: ConfigMap
metadata:
  name: api
data:
  application.yaml: |-  
    management: 
      apis:
      - uri: /api/test/.*
        methods:
        - POST
        - PUT
        - PATCH
        - DELETE
        roles:
        - ADMIN
      - uri: /api/order/.*
        methods:
        - POST
        - PUT
        - PATCH
        - DELETE
        roles:
        - ADMIN
      - uri: /api/cluster/.*
        methods:
        - POST
        - PUT
        - PATCH
        - DELETE
        roles:
        - ADMIN
      - uri: /api/customer/.*
        methods:
        - POST
        - PUT
        - PATCH
        - DELETE
        roles:
        - ADMIN
  