apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kong-test
  name: configmap-reload
  labels:
    app: configmap-reload
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: kong-test
  name: configmap-reload
  labels:
    app: configmap-reload
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: kong-test
  name: configmap-reload
  labels:
    app: configmap-reload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-reload
subjects:
- kind: ServiceAccount
  namespace: kong-test
  name: configmap-reload
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: configmap-reload
  labels:
    app: configmap-reload
spec:
  selector:
    matchLabels:
      app: configmap-reload
  replicas: 1
  template:
    metadata:
      labels:
        app: configmap-reload
    spec:
      serviceAccountName: configmap-reload
      containers:
      - name: configmap-reload
        image: pog-dev-registry.cloudzcp.io/zcp-estimate/configmap-reload:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: configmap-reload
spec:
  selector:
    app: configmap-reload
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
        